spring:
  application:
    name: Unified-Marketing-Gateway
  config:
    import: "optional:classpath:application-secrets.yaml"

telegram:
  baseUrl: https://api.telegram.org
  maxConcurrency: 8
  contentBasedResource:
    text:
      isEnabled: true
      path: sendMessage
    image:
      local:
        isEnabled: false
        path: sendPhoto
      remote:
        isEnabled: false
        path: sendPhoto
    video:
      isEnabled: false
      path: sendVideo
  group:
    - chatID: "-4871935676"
    - chatID: "8146034511"
    - chatID: "7642285695"
  retry:
    maxRetryCount: 4
    initialBackoff: 1
    maxBackoff: 30

