spring:
  application:
    name: Unified-Marketing-Gateway

telegram:
  baseUrl: https://api.telegram.org
  contentBasedResource:
    text:
      isEnabled: true
      path: sendMessage
    image:
      local:
        isEnabled: false
        path: sendPhoto
      remote:
        isEnabled: false
        path: sendPhoto
    video:
      isEnabled: false
      path: sendVideo
  bot:
    token:
  group:
    - chatID: "-4871935676"
    - chatID: "8146034511"
    - chatID: "7642285695"

