#Steps to create your own application-secrets.yaml:
#  1. Create a file src/main/resources/application-secrets.yaml
#  2. Add the below configuration in your application-secrets.yaml
#  3. Replace the placeholder value with your telegram token

telegram:
  bot:
    token: <Paste Your Telegram Token Here>

whatsapp:
  accessToken: <Paste Your Whatsapp Access Token Here>
  phone-number-id: <Paste Your WHATSAPP_BUSINESS_PHONE_NUMBER_ID Here>
