spring:
  application:
    name: Unified-Marketing-Gateway
  config:
    import: "optional:classpath:application-secrets.yaml"


#Add only Telegram related configs below this line
telegram:
  baseUrl: https://api.telegram.org
  maxConcurrency: 8
  contentBasedResource:
    text:
      isEnabled: true
    image:
      isEnabled: false
    video:
      isEnabled: false
  retry:
    maxRetryCount: 4
    initialBackoff: 1
    maxBackoff: 30

#Add only Whatsapp related configs below this line
whatsapp:
  baseUrl: https://graph.facebook.com
  api-version: "v20.0"
  maxConcurrency: 8
  retry:
    maxRetryCount: 4
    initialBackoff: 1
    maxBackoff: 30
  contentBasedResource:
    text:
      isEnabled: false
    image:
      isEnabled: false
    video:
      isEnabled: false